// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module FFT_FFT_stage_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        data_OUT_address0,
        data_OUT_ce0,
        data_OUT_we0,
        data_OUT_d0,
        data_OUT_address1,
        data_OUT_ce1,
        data_OUT_we1,
        data_OUT_d1,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_42,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_31,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_94,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_15,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_79,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_30,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_95,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_14,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_80,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_29,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_96,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_13,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_81,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_28,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_97,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_12,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_82,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_27,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_98,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_11,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_83,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_26,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_99,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_10,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_84,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_25,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_41,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_9,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_85,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_24,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_40,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_8,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_86,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_23,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_39,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_7,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_87,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_22,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_38,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_6,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_88,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_21,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_37,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_5,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_89,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_20,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_36,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_4,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_90,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_19,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_35,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_3,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_91,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_18,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_34,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_2,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_92,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_17,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_33,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_1,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_93,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_16,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_32,
        FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4
);

parameter    ap_ST_fsm_state1 = 17'd1;
parameter    ap_ST_fsm_state2 = 17'd2;
parameter    ap_ST_fsm_state3 = 17'd4;
parameter    ap_ST_fsm_state4 = 17'd8;
parameter    ap_ST_fsm_state5 = 17'd16;
parameter    ap_ST_fsm_state6 = 17'd32;
parameter    ap_ST_fsm_state7 = 17'd64;
parameter    ap_ST_fsm_state8 = 17'd128;
parameter    ap_ST_fsm_state9 = 17'd256;
parameter    ap_ST_fsm_state10 = 17'd512;
parameter    ap_ST_fsm_state11 = 17'd1024;
parameter    ap_ST_fsm_state12 = 17'd2048;
parameter    ap_ST_fsm_state13 = 17'd4096;
parameter    ap_ST_fsm_state14 = 17'd8192;
parameter    ap_ST_fsm_state15 = 17'd16384;
parameter    ap_ST_fsm_state16 = 17'd32768;
parameter    ap_ST_fsm_state17 = 17'd65536;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [4:0] data_OUT_address0;
output   data_OUT_ce0;
output   data_OUT_we0;
output  [31:0] data_OUT_d0;
output  [4:0] data_OUT_address1;
output   data_OUT_ce1;
output   data_OUT_we1;
output  [31:0] data_OUT_d1;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_42;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_31;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_94;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_15;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_79;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_30;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_95;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_14;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_80;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_29;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_96;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_13;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_81;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_28;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_97;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_12;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_82;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_27;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_98;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_11;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_83;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_26;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_99;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_10;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_84;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_25;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_41;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_9;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_85;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_24;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_40;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_8;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_86;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_23;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_39;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_7;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_87;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_22;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_38;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_6;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_88;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_21;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_37;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_5;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_89;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_20;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_36;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_4;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_90;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_19;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_35;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_3;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_91;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_18;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_34;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_2;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_92;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_17;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_33;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_1;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_93;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_16;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_32;
input  [15:0] FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[4:0] data_OUT_address0;
reg data_OUT_ce0;
reg data_OUT_we0;
reg[31:0] data_OUT_d0;
reg[4:0] data_OUT_address1;
reg data_OUT_ce1;
reg data_OUT_we1;
reg[31:0] data_OUT_d1;

(* fsm_encoding = "none" *) reg   [16:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire  signed [23:0] sext_ln389_6_fu_637_p1;
reg  signed [23:0] sext_ln389_6_reg_2391;
wire    ap_CS_fsm_state2;
wire  signed [23:0] sext_ln389_7_fu_641_p1;
reg  signed [23:0] sext_ln389_7_reg_2397;
wire  signed [23:0] mul_ln389_fu_730_p2;
wire    ap_CS_fsm_state3;
wire  signed [23:0] mul_ln389_2_fu_739_p2;
wire  signed [23:0] sext_ln389_8_fu_753_p1;
reg  signed [23:0] sext_ln389_8_reg_2413;
wire  signed [23:0] sext_ln389_9_fu_757_p1;
reg  signed [23:0] sext_ln389_9_reg_2419;
wire  signed [23:0] mul_ln389_4_fu_829_p2;
wire    ap_CS_fsm_state4;
wire  signed [23:0] mul_ln389_6_fu_834_p2;
wire  signed [23:0] sext_ln389_10_fu_847_p1;
reg  signed [23:0] sext_ln389_10_reg_2435;
wire  signed [23:0] sext_ln389_11_fu_851_p1;
reg  signed [23:0] sext_ln389_11_reg_2441;
wire  signed [23:0] mul_ln389_8_fu_923_p2;
wire    ap_CS_fsm_state5;
wire  signed [23:0] mul_ln389_10_fu_928_p2;
wire  signed [23:0] sext_ln389_12_fu_941_p1;
reg  signed [23:0] sext_ln389_12_reg_2457;
wire  signed [23:0] sext_ln389_13_fu_945_p1;
reg  signed [23:0] sext_ln389_13_reg_2463;
wire  signed [23:0] mul_ln389_12_fu_1017_p2;
wire    ap_CS_fsm_state6;
wire  signed [23:0] mul_ln389_14_fu_1022_p2;
wire  signed [23:0] sext_ln389_14_fu_1035_p1;
reg  signed [23:0] sext_ln389_14_reg_2479;
wire  signed [23:0] sext_ln389_15_fu_1039_p1;
reg  signed [23:0] sext_ln389_15_reg_2485;
wire  signed [23:0] mul_ln389_16_fu_1111_p2;
wire    ap_CS_fsm_state7;
wire  signed [23:0] mul_ln389_18_fu_1116_p2;
wire  signed [23:0] mul_ln389_20_fu_1205_p2;
wire    ap_CS_fsm_state8;
wire  signed [23:0] mul_ln389_22_fu_1210_p2;
wire    ap_CS_fsm_state9;
wire  signed [23:0] sext_ln389_28_fu_1355_p1;
reg  signed [23:0] sext_ln389_28_reg_2553;
wire  signed [23:0] sext_ln389_29_fu_1359_p1;
reg  signed [23:0] sext_ln389_29_reg_2559;
wire    ap_CS_fsm_state10;
wire  signed [23:0] sext_ln389_30_fu_1487_p1;
reg  signed [23:0] sext_ln389_30_reg_2575;
wire  signed [23:0] sext_ln389_31_fu_1491_p1;
reg  signed [23:0] sext_ln389_31_reg_2581;
wire  signed [23:0] mul_ln389_28_fu_1563_p2;
wire    ap_CS_fsm_state11;
wire  signed [23:0] mul_ln389_30_fu_1568_p2;
wire  signed [23:0] mul_ln389_32_fu_1657_p2;
wire    ap_CS_fsm_state12;
wire  signed [23:0] mul_ln389_34_fu_1662_p2;
wire  signed [23:0] sext_ln389_34_fu_1675_p1;
reg  signed [23:0] sext_ln389_34_reg_2607;
wire  signed [23:0] sext_ln389_35_fu_1679_p1;
reg  signed [23:0] sext_ln389_35_reg_2613;
wire  signed [23:0] sext_ln389_36_fu_1759_p1;
reg  signed [23:0] sext_ln389_36_reg_2619;
wire    ap_CS_fsm_state13;
wire  signed [23:0] sext_ln389_37_fu_1763_p1;
reg  signed [23:0] sext_ln389_37_reg_2625;
wire  signed [23:0] mul_ln389_38_fu_1835_p2;
wire    ap_CS_fsm_state14;
wire  signed [23:0] mul_ln389_40_fu_1840_p2;
wire  signed [23:0] mul_ln389_42_fu_1929_p2;
wire    ap_CS_fsm_state15;
wire  signed [23:0] mul_ln389_44_fu_1934_p2;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state17;
wire   [31:0] conv_i2_i66_i_i_partset_fu_583_p3;
wire   [31:0] conv_i2_i66_i_i83_partset_fu_604_p3;
wire   [31:0] conv_i2_i66_i_i_partset_8_fu_697_p3;
wire   [31:0] conv_i2_i66_i_i83_partset_8_fu_718_p3;
wire   [31:0] conv_i2_i66_i_i_partset_1_fu_799_p3;
wire   [31:0] conv_i2_i66_i_i83_partset_1_fu_820_p3;
wire   [31:0] conv_i2_i66_i_i_partset_2_fu_893_p3;
wire   [31:0] conv_i2_i66_i_i83_partset_2_fu_914_p3;
wire   [31:0] conv_i2_i66_i_i_partset_3_fu_987_p3;
wire   [31:0] conv_i2_i66_i_i83_partset_3_fu_1008_p3;
wire   [31:0] conv_i2_i66_i_i_partset_4_fu_1081_p3;
wire   [31:0] conv_i2_i66_i_i83_partset_4_fu_1102_p3;
wire   [31:0] conv_i2_i66_i_i_partset_5_fu_1175_p3;
wire   [31:0] conv_i2_i66_i_i83_partset_5_fu_1196_p3;
wire   [31:0] conv_i2_i66_i_i_partset_6_fu_1269_p3;
wire   [31:0] conv_i2_i66_i_i83_partset_6_fu_1290_p3;
wire   [31:0] conv_i2_i66_i_i_partset_7_fu_1401_p3;
wire   [31:0] conv_i2_i66_i_i83_partset_7_fu_1422_p3;
wire   [31:0] conv_i2_i66_i_i_partset_9_fu_1533_p3;
wire   [31:0] conv_i2_i66_i_i83_partset_9_fu_1554_p3;
wire   [31:0] conv_i2_i66_i_i_partset_s_fu_1627_p3;
wire   [31:0] conv_i2_i66_i_i83_partset_s_fu_1648_p3;
wire   [31:0] conv_i2_i66_i_i_partset_10_fu_1721_p3;
wire   [31:0] conv_i2_i66_i_i83_partset_10_fu_1742_p3;
wire   [31:0] conv_i2_i66_i_i_partset_11_fu_1805_p3;
wire   [31:0] conv_i2_i66_i_i83_partset_11_fu_1826_p3;
wire   [31:0] conv_i2_i66_i_i_partset_12_fu_1899_p3;
wire   [31:0] conv_i2_i66_i_i83_partset_12_fu_1920_p3;
wire   [31:0] conv_i2_i66_i_i_partset_13_fu_1977_p3;
wire   [31:0] conv_i2_i66_i_i83_partset_13_fu_1998_p3;
wire   [31:0] conv_i2_i66_i_i_partset_14_fu_2093_p3;
wire   [31:0] conv_i2_i66_i_i83_partset_14_fu_2114_p3;
wire   [15:0] p_r_M_imag_1_fu_577_p2;
wire   [15:0] p_r_M_real_1_fu_571_p2;
wire   [15:0] p_r_M_imag_2_fu_598_p2;
wire   [15:0] p_r_M_real_2_fu_592_p2;
wire   [23:0] shl_ln389_4_fu_661_p3;
wire   [23:0] sub_ln389_3_fu_669_p2;
wire   [15:0] trunc_ln389_13_fu_675_p4;
wire   [15:0] p_r_M_imag_25_fu_691_p2;
wire   [15:0] p_r_M_real_25_fu_685_p2;
wire   [15:0] p_r_M_imag_26_fu_712_p2;
wire   [15:0] p_r_M_real_26_fu_706_p2;
wire   [8:0] mul_ln389_fu_730_p1;
wire   [8:0] mul_ln389_2_fu_739_p1;
wire  signed [23:0] grp_fu_2123_p3;
wire  signed [23:0] grp_fu_2132_p3;
wire   [15:0] trunc_ln_fu_769_p4;
wire   [15:0] trunc_ln389_1_fu_778_p4;
wire   [15:0] p_r_M_imag_4_fu_793_p2;
wire   [15:0] p_r_M_real_4_fu_787_p2;
wire   [15:0] p_r_M_imag_5_fu_814_p2;
wire   [15:0] p_r_M_real_5_fu_808_p2;
wire  signed [15:0] mul_ln389_4_fu_829_p0;
wire   [8:0] mul_ln389_4_fu_829_p1;
wire  signed [15:0] mul_ln389_6_fu_834_p0;
wire   [8:0] mul_ln389_6_fu_834_p1;
wire  signed [23:0] grp_fu_2141_p3;
wire  signed [23:0] grp_fu_2150_p3;
wire   [15:0] trunc_ln389_2_fu_863_p4;
wire   [15:0] trunc_ln389_3_fu_872_p4;
wire   [15:0] p_r_M_imag_7_fu_887_p2;
wire   [15:0] p_r_M_real_7_fu_881_p2;
wire   [15:0] p_r_M_imag_8_fu_908_p2;
wire   [15:0] p_r_M_real_8_fu_902_p2;
wire  signed [15:0] mul_ln389_8_fu_923_p0;
wire   [8:0] mul_ln389_8_fu_923_p1;
wire  signed [15:0] mul_ln389_10_fu_928_p0;
wire   [8:0] mul_ln389_10_fu_928_p1;
wire  signed [23:0] grp_fu_2159_p3;
wire  signed [23:0] grp_fu_2168_p3;
wire   [15:0] trunc_ln389_4_fu_957_p4;
wire   [15:0] trunc_ln389_5_fu_966_p4;
wire   [15:0] p_r_M_imag_10_fu_981_p2;
wire   [15:0] p_r_M_real_10_fu_975_p2;
wire   [15:0] p_r_M_imag_11_fu_1002_p2;
wire   [15:0] p_r_M_real_11_fu_996_p2;
wire  signed [15:0] mul_ln389_12_fu_1017_p0;
wire   [8:0] mul_ln389_12_fu_1017_p1;
wire  signed [15:0] mul_ln389_14_fu_1022_p0;
wire   [8:0] mul_ln389_14_fu_1022_p1;
wire  signed [23:0] grp_fu_2177_p3;
wire  signed [23:0] grp_fu_2186_p3;
wire   [15:0] trunc_ln389_6_fu_1051_p4;
wire   [15:0] trunc_ln389_7_fu_1060_p4;
wire   [15:0] p_r_M_imag_13_fu_1075_p2;
wire   [15:0] p_r_M_real_13_fu_1069_p2;
wire   [15:0] p_r_M_imag_14_fu_1096_p2;
wire   [15:0] p_r_M_real_14_fu_1090_p2;
wire  signed [15:0] mul_ln389_16_fu_1111_p0;
wire   [8:0] mul_ln389_16_fu_1111_p1;
wire  signed [15:0] mul_ln389_18_fu_1116_p0;
wire   [8:0] mul_ln389_18_fu_1116_p1;
wire  signed [23:0] grp_fu_2195_p3;
wire  signed [23:0] grp_fu_2204_p3;
wire   [15:0] trunc_ln389_8_fu_1145_p4;
wire   [15:0] trunc_ln389_9_fu_1154_p4;
wire   [15:0] p_r_M_imag_16_fu_1169_p2;
wire   [15:0] p_r_M_real_16_fu_1163_p2;
wire   [15:0] p_r_M_imag_17_fu_1190_p2;
wire   [15:0] p_r_M_real_17_fu_1184_p2;
wire  signed [15:0] mul_ln389_20_fu_1205_p0;
wire   [7:0] mul_ln389_20_fu_1205_p1;
wire  signed [15:0] mul_ln389_22_fu_1210_p0;
wire   [7:0] mul_ln389_22_fu_1210_p1;
wire  signed [23:0] grp_fu_2213_p3;
wire  signed [23:0] grp_fu_2222_p3;
wire   [15:0] trunc_ln389_s_fu_1239_p4;
wire   [15:0] trunc_ln389_10_fu_1248_p4;
wire   [15:0] p_r_M_imag_19_fu_1263_p2;
wire   [15:0] p_r_M_real_19_fu_1257_p2;
wire   [15:0] p_r_M_imag_20_fu_1284_p2;
wire   [15:0] p_r_M_real_20_fu_1278_p2;
wire  signed [15:0] shl_ln_fu_1299_p1;
wire  signed [15:0] shl_ln389_1_fu_1306_p1;
wire   [17:0] shl_ln389_1_fu_1306_p3;
wire   [23:0] shl_ln_fu_1299_p3;
wire  signed [23:0] sext_ln389_18_fu_1313_p1;
wire  signed [15:0] shl_ln389_2_fu_1323_p1;
wire  signed [15:0] shl_ln389_3_fu_1330_p1;
wire   [17:0] shl_ln389_3_fu_1330_p3;
wire  signed [23:0] sext_ln389_20_fu_1337_p1;
wire   [23:0] shl_ln389_2_fu_1323_p3;
wire  signed [23:0] grp_fu_2231_p3;
wire  signed [23:0] grp_fu_2240_p3;
wire   [15:0] trunc_ln389_11_fu_1371_p4;
wire   [15:0] trunc_ln389_12_fu_1380_p4;
wire   [15:0] p_r_M_imag_22_fu_1395_p2;
wire   [15:0] p_r_M_real_22_fu_1389_p2;
wire   [15:0] p_r_M_imag_23_fu_1416_p2;
wire   [15:0] p_r_M_real_23_fu_1410_p2;
wire  signed [15:0] shl_ln389_5_fu_1431_p1;
wire  signed [15:0] shl_ln389_6_fu_1438_p1;
wire   [17:0] shl_ln389_6_fu_1438_p3;
wire   [23:0] shl_ln389_5_fu_1431_p3;
wire  signed [23:0] sext_ln389_24_fu_1445_p1;
wire  signed [15:0] shl_ln389_7_fu_1455_p1;
wire  signed [15:0] shl_ln389_8_fu_1462_p1;
wire   [17:0] shl_ln389_8_fu_1462_p3;
wire  signed [23:0] sext_ln389_26_fu_1469_p1;
wire   [23:0] shl_ln389_7_fu_1455_p3;
wire  signed [23:0] grp_fu_2249_p3;
wire  signed [23:0] grp_fu_2258_p3;
wire   [15:0] trunc_ln389_14_fu_1503_p4;
wire   [15:0] trunc_ln389_15_fu_1512_p4;
wire   [15:0] p_r_M_imag_28_fu_1527_p2;
wire   [15:0] p_r_M_real_28_fu_1521_p2;
wire   [15:0] p_r_M_imag_29_fu_1548_p2;
wire   [15:0] p_r_M_real_29_fu_1542_p2;
wire  signed [15:0] mul_ln389_28_fu_1563_p0;
wire  signed [7:0] mul_ln389_28_fu_1563_p1;
wire  signed [15:0] mul_ln389_30_fu_1568_p0;
wire  signed [7:0] mul_ln389_30_fu_1568_p1;
wire  signed [23:0] grp_fu_2267_p3;
wire  signed [23:0] grp_fu_2276_p3;
wire   [15:0] trunc_ln389_16_fu_1597_p4;
wire   [15:0] trunc_ln389_17_fu_1606_p4;
wire   [15:0] p_r_M_imag_31_fu_1621_p2;
wire   [15:0] p_r_M_real_31_fu_1615_p2;
wire   [15:0] p_r_M_imag_32_fu_1642_p2;
wire   [15:0] p_r_M_real_32_fu_1636_p2;
wire  signed [15:0] mul_ln389_32_fu_1657_p0;
wire  signed [8:0] mul_ln389_32_fu_1657_p1;
wire  signed [15:0] mul_ln389_34_fu_1662_p0;
wire  signed [8:0] mul_ln389_34_fu_1662_p1;
wire  signed [23:0] grp_fu_2285_p3;
wire  signed [23:0] grp_fu_2294_p3;
wire   [15:0] trunc_ln389_18_fu_1691_p4;
wire   [15:0] trunc_ln389_19_fu_1700_p4;
wire   [15:0] p_r_M_imag_34_fu_1715_p2;
wire   [15:0] p_r_M_real_34_fu_1709_p2;
wire   [15:0] p_r_M_imag_35_fu_1736_p2;
wire   [15:0] p_r_M_real_35_fu_1730_p2;
wire  signed [23:0] grp_fu_2303_p3;
wire  signed [23:0] grp_fu_2312_p3;
wire   [15:0] trunc_ln389_20_fu_1775_p4;
wire   [15:0] trunc_ln389_21_fu_1784_p4;
wire   [15:0] p_r_M_imag_37_fu_1799_p2;
wire   [15:0] p_r_M_real_37_fu_1793_p2;
wire   [15:0] p_r_M_imag_38_fu_1820_p2;
wire   [15:0] p_r_M_real_38_fu_1814_p2;
wire  signed [15:0] mul_ln389_38_fu_1835_p0;
wire  signed [8:0] mul_ln389_38_fu_1835_p1;
wire  signed [15:0] mul_ln389_40_fu_1840_p0;
wire  signed [8:0] mul_ln389_40_fu_1840_p1;
wire  signed [23:0] grp_fu_2321_p3;
wire  signed [23:0] grp_fu_2330_p3;
wire   [15:0] trunc_ln389_22_fu_1869_p4;
wire   [15:0] trunc_ln389_23_fu_1878_p4;
wire   [15:0] p_r_M_imag_40_fu_1893_p2;
wire   [15:0] p_r_M_real_40_fu_1887_p2;
wire   [15:0] p_r_M_imag_41_fu_1914_p2;
wire   [15:0] p_r_M_real_41_fu_1908_p2;
wire  signed [15:0] mul_ln389_42_fu_1929_p0;
wire  signed [8:0] mul_ln389_42_fu_1929_p1;
wire  signed [15:0] mul_ln389_44_fu_1934_p0;
wire  signed [8:0] mul_ln389_44_fu_1934_p1;
wire  signed [23:0] grp_fu_2339_p3;
wire  signed [23:0] grp_fu_2348_p3;
wire   [15:0] trunc_ln389_24_fu_1947_p4;
wire   [15:0] trunc_ln389_25_fu_1956_p4;
wire   [15:0] p_r_M_imag_43_fu_1971_p2;
wire   [15:0] p_r_M_real_43_fu_1965_p2;
wire   [15:0] p_r_M_imag_44_fu_1992_p2;
wire   [15:0] p_r_M_real_44_fu_1986_p2;
wire  signed [15:0] shl_ln389_9_fu_2007_p1;
wire  signed [15:0] shl_ln389_s_fu_2014_p1;
wire   [17:0] shl_ln389_s_fu_2014_p3;
wire  signed [23:0] sext_ln389_39_fu_2021_p1;
wire   [23:0] shl_ln389_9_fu_2007_p3;
wire  signed [15:0] shl_ln389_10_fu_2031_p1;
wire  signed [15:0] shl_ln389_11_fu_2038_p1;
wire   [17:0] shl_ln389_11_fu_2038_p3;
wire  signed [23:0] sext_ln389_42_fu_2045_p1;
wire   [23:0] shl_ln389_10_fu_2031_p3;
wire  signed [23:0] grp_fu_2357_p3;
wire  signed [23:0] grp_fu_2366_p3;
wire   [15:0] trunc_ln389_26_fu_2063_p4;
wire   [15:0] trunc_ln389_27_fu_2072_p4;
wire   [15:0] p_r_M_imag_46_fu_2087_p2;
wire   [15:0] p_r_M_real_46_fu_2081_p2;
wire   [15:0] p_r_M_imag_47_fu_2108_p2;
wire   [15:0] p_r_M_real_47_fu_2102_p2;
wire  signed [6:0] grp_fu_2123_p1;
wire  signed [6:0] grp_fu_2132_p1;
wire   [6:0] grp_fu_2141_p1;
wire  signed [7:0] grp_fu_2150_p1;
wire   [7:0] grp_fu_2159_p1;
wire  signed [8:0] grp_fu_2168_p1;
wire   [7:0] grp_fu_2177_p1;
wire  signed [8:0] grp_fu_2186_p1;
wire   [7:0] grp_fu_2195_p1;
wire  signed [8:0] grp_fu_2204_p1;
wire   [7:0] grp_fu_2213_p1;
wire  signed [8:0] grp_fu_2222_p1;
wire   [5:0] grp_fu_2231_p1;
wire  signed [23:0] grp_fu_2231_p2;
wire   [5:0] grp_fu_2240_p1;
wire  signed [23:0] grp_fu_2240_p2;
wire  signed [6:0] grp_fu_2249_p1;
wire  signed [23:0] grp_fu_2249_p2;
wire  signed [6:0] grp_fu_2258_p1;
wire  signed [23:0] grp_fu_2258_p2;
wire   [7:0] grp_fu_2267_p1;
wire  signed [8:0] grp_fu_2276_p1;
wire   [7:0] grp_fu_2285_p1;
wire  signed [8:0] grp_fu_2294_p1;
wire  signed [15:0] grp_fu_2303_p0;
wire  signed [16:0] sext_ln389_32_fu_1581_p1;
wire  signed [15:0] grp_fu_2303_p1;
wire  signed [16:0] sext_ln389_33_fu_1585_p1;
wire  signed [8:0] grp_fu_2303_p2;
wire  signed [15:0] grp_fu_2312_p0;
wire  signed [15:0] grp_fu_2312_p1;
wire  signed [8:0] grp_fu_2312_p2;
wire   [7:0] grp_fu_2321_p1;
wire  signed [8:0] grp_fu_2330_p1;
wire   [6:0] grp_fu_2339_p1;
wire  signed [7:0] grp_fu_2348_p1;
wire  signed [6:0] grp_fu_2357_p1;
wire  signed [23:0] grp_fu_2357_p2;
wire  signed [6:0] grp_fu_2366_p1;
wire  signed [23:0] grp_fu_2366_p2;
reg   [16:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 17'd1;
end

FFT_mul_16s_9ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 24 ))
mul_16s_9ns_24_1_1_U261(
    .din0(FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_95),
    .din1(mul_ln389_fu_730_p1),
    .dout(mul_ln389_fu_730_p2)
);

FFT_mul_16s_9ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 24 ))
mul_16s_9ns_24_1_1_U262(
    .din0(FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_14),
    .din1(mul_ln389_2_fu_739_p1),
    .dout(mul_ln389_2_fu_739_p2)
);

FFT_mul_16s_9ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 24 ))
mul_16s_9ns_24_1_1_U263(
    .din0(mul_ln389_4_fu_829_p0),
    .din1(mul_ln389_4_fu_829_p1),
    .dout(mul_ln389_4_fu_829_p2)
);

FFT_mul_16s_9ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 24 ))
mul_16s_9ns_24_1_1_U264(
    .din0(mul_ln389_6_fu_834_p0),
    .din1(mul_ln389_6_fu_834_p1),
    .dout(mul_ln389_6_fu_834_p2)
);

FFT_mul_16s_9ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 24 ))
mul_16s_9ns_24_1_1_U265(
    .din0(mul_ln389_8_fu_923_p0),
    .din1(mul_ln389_8_fu_923_p1),
    .dout(mul_ln389_8_fu_923_p2)
);

FFT_mul_16s_9ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 24 ))
mul_16s_9ns_24_1_1_U266(
    .din0(mul_ln389_10_fu_928_p0),
    .din1(mul_ln389_10_fu_928_p1),
    .dout(mul_ln389_10_fu_928_p2)
);

FFT_mul_16s_9ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 24 ))
mul_16s_9ns_24_1_1_U267(
    .din0(mul_ln389_12_fu_1017_p0),
    .din1(mul_ln389_12_fu_1017_p1),
    .dout(mul_ln389_12_fu_1017_p2)
);

FFT_mul_16s_9ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 24 ))
mul_16s_9ns_24_1_1_U268(
    .din0(mul_ln389_14_fu_1022_p0),
    .din1(mul_ln389_14_fu_1022_p1),
    .dout(mul_ln389_14_fu_1022_p2)
);

FFT_mul_16s_9ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 24 ))
mul_16s_9ns_24_1_1_U269(
    .din0(mul_ln389_16_fu_1111_p0),
    .din1(mul_ln389_16_fu_1111_p1),
    .dout(mul_ln389_16_fu_1111_p2)
);

FFT_mul_16s_9ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 24 ))
mul_16s_9ns_24_1_1_U270(
    .din0(mul_ln389_18_fu_1116_p0),
    .din1(mul_ln389_18_fu_1116_p1),
    .dout(mul_ln389_18_fu_1116_p2)
);

FFT_mul_16s_8ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_16s_8ns_24_1_1_U271(
    .din0(mul_ln389_20_fu_1205_p0),
    .din1(mul_ln389_20_fu_1205_p1),
    .dout(mul_ln389_20_fu_1205_p2)
);

FFT_mul_16s_8ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_16s_8ns_24_1_1_U272(
    .din0(mul_ln389_22_fu_1210_p0),
    .din1(mul_ln389_22_fu_1210_p1),
    .dout(mul_ln389_22_fu_1210_p2)
);

FFT_mul_16s_8s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_16s_8s_24_1_1_U273(
    .din0(mul_ln389_28_fu_1563_p0),
    .din1(mul_ln389_28_fu_1563_p1),
    .dout(mul_ln389_28_fu_1563_p2)
);

FFT_mul_16s_8s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_16s_8s_24_1_1_U274(
    .din0(mul_ln389_30_fu_1568_p0),
    .din1(mul_ln389_30_fu_1568_p1),
    .dout(mul_ln389_30_fu_1568_p2)
);

FFT_mul_16s_9s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 24 ))
mul_16s_9s_24_1_1_U275(
    .din0(mul_ln389_32_fu_1657_p0),
    .din1(mul_ln389_32_fu_1657_p1),
    .dout(mul_ln389_32_fu_1657_p2)
);

FFT_mul_16s_9s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 24 ))
mul_16s_9s_24_1_1_U276(
    .din0(mul_ln389_34_fu_1662_p0),
    .din1(mul_ln389_34_fu_1662_p1),
    .dout(mul_ln389_34_fu_1662_p2)
);

FFT_mul_16s_9s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 24 ))
mul_16s_9s_24_1_1_U277(
    .din0(mul_ln389_38_fu_1835_p0),
    .din1(mul_ln389_38_fu_1835_p1),
    .dout(mul_ln389_38_fu_1835_p2)
);

FFT_mul_16s_9s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 24 ))
mul_16s_9s_24_1_1_U278(
    .din0(mul_ln389_40_fu_1840_p0),
    .din1(mul_ln389_40_fu_1840_p1),
    .dout(mul_ln389_40_fu_1840_p2)
);

FFT_mul_16s_9s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 24 ))
mul_16s_9s_24_1_1_U279(
    .din0(mul_ln389_42_fu_1929_p0),
    .din1(mul_ln389_42_fu_1929_p1),
    .dout(mul_ln389_42_fu_1929_p2)
);

FFT_mul_16s_9s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 24 ))
mul_16s_9s_24_1_1_U280(
    .din0(mul_ln389_44_fu_1934_p0),
    .din1(mul_ln389_44_fu_1934_p1),
    .dout(mul_ln389_44_fu_1934_p2)
);

FFT_mac_mulsub_16s_7s_24s_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_mulsub_16s_7s_24s_24_4_1_U281(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_14),
    .din1(grp_fu_2123_p1),
    .din2(mul_ln389_fu_730_p2),
    .ce(1'b1),
    .dout(grp_fu_2123_p3)
);

FFT_mac_muladd_16s_7s_24s_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_7s_24s_24_4_1_U282(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_95),
    .din1(grp_fu_2132_p1),
    .din2(mul_ln389_2_fu_739_p2),
    .ce(1'b1),
    .dout(grp_fu_2132_p3)
);

FFT_mac_muladd_16s_7ns_24s_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_7ns_24s_24_4_1_U283(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_13),
    .din1(grp_fu_2141_p1),
    .din2(mul_ln389_4_fu_829_p2),
    .ce(1'b1),
    .dout(grp_fu_2141_p3)
);

FFT_mac_muladd_16s_8s_24s_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_8s_24s_24_4_1_U284(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_96),
    .din1(grp_fu_2150_p1),
    .din2(mul_ln389_6_fu_834_p2),
    .ce(1'b1),
    .dout(grp_fu_2150_p3)
);

FFT_mac_muladd_16s_8ns_24s_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_8ns_24s_24_4_1_U285(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_12),
    .din1(grp_fu_2159_p1),
    .din2(mul_ln389_8_fu_923_p2),
    .ce(1'b1),
    .dout(grp_fu_2159_p3)
);

FFT_mac_muladd_16s_9s_24s_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_9s_24s_24_4_1_U286(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_97),
    .din1(grp_fu_2168_p1),
    .din2(mul_ln389_10_fu_928_p2),
    .ce(1'b1),
    .dout(grp_fu_2168_p3)
);

FFT_mac_muladd_16s_8ns_24s_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_8ns_24s_24_4_1_U287(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_11),
    .din1(grp_fu_2177_p1),
    .din2(mul_ln389_12_fu_1017_p2),
    .ce(1'b1),
    .dout(grp_fu_2177_p3)
);

FFT_mac_muladd_16s_9s_24s_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_9s_24s_24_4_1_U288(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_98),
    .din1(grp_fu_2186_p1),
    .din2(mul_ln389_14_fu_1022_p2),
    .ce(1'b1),
    .dout(grp_fu_2186_p3)
);

FFT_mac_muladd_16s_8ns_24s_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_8ns_24s_24_4_1_U289(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_10),
    .din1(grp_fu_2195_p1),
    .din2(mul_ln389_16_fu_1111_p2),
    .ce(1'b1),
    .dout(grp_fu_2195_p3)
);

FFT_mac_muladd_16s_9s_24s_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_9s_24s_24_4_1_U290(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_99),
    .din1(grp_fu_2204_p1),
    .din2(mul_ln389_18_fu_1116_p2),
    .ce(1'b1),
    .dout(grp_fu_2204_p3)
);

FFT_mac_muladd_16s_8ns_24s_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_8ns_24s_24_4_1_U291(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_9),
    .din1(grp_fu_2213_p1),
    .din2(mul_ln389_20_fu_1205_p2),
    .ce(1'b1),
    .dout(grp_fu_2213_p3)
);

FFT_mac_muladd_16s_9s_24s_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_9s_24s_24_4_1_U292(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_41),
    .din1(grp_fu_2222_p1),
    .din2(mul_ln389_22_fu_1210_p2),
    .ce(1'b1),
    .dout(grp_fu_2222_p3)
);

FFT_mac_muladd_16s_6ns_24s_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_6ns_24s_24_4_1_U293(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_40),
    .din1(grp_fu_2231_p1),
    .din2(grp_fu_2231_p2),
    .ce(1'b1),
    .dout(grp_fu_2231_p3)
);

FFT_mac_muladd_16s_6ns_24s_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_6ns_24s_24_4_1_U294(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_8),
    .din1(grp_fu_2240_p1),
    .din2(grp_fu_2240_p2),
    .ce(1'b1),
    .dout(grp_fu_2240_p3)
);

FFT_mac_muladd_16s_7s_24s_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_7s_24s_24_4_1_U295(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_38),
    .din1(grp_fu_2249_p1),
    .din2(grp_fu_2249_p2),
    .ce(1'b1),
    .dout(grp_fu_2249_p3)
);

FFT_mac_muladd_16s_7s_24s_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_7s_24s_24_4_1_U296(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_6),
    .din1(grp_fu_2258_p1),
    .din2(grp_fu_2258_p2),
    .ce(1'b1),
    .dout(grp_fu_2258_p3)
);

FFT_mac_muladd_16s_8ns_24s_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_8ns_24s_24_4_1_U297(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_5),
    .din1(grp_fu_2267_p1),
    .din2(mul_ln389_28_fu_1563_p2),
    .ce(1'b1),
    .dout(grp_fu_2267_p3)
);

FFT_mac_muladd_16s_9s_24s_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_9s_24s_24_4_1_U298(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_37),
    .din1(grp_fu_2276_p1),
    .din2(mul_ln389_30_fu_1568_p2),
    .ce(1'b1),
    .dout(grp_fu_2276_p3)
);

FFT_mac_muladd_16s_8ns_24s_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_8ns_24s_24_4_1_U299(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_4),
    .din1(grp_fu_2285_p1),
    .din2(mul_ln389_32_fu_1657_p2),
    .ce(1'b1),
    .dout(grp_fu_2285_p3)
);

FFT_mac_muladd_16s_9s_24s_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_9s_24s_24_4_1_U300(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_36),
    .din1(grp_fu_2294_p1),
    .din2(mul_ln389_34_fu_1662_p2),
    .ce(1'b1),
    .dout(grp_fu_2294_p3)
);

FFT_am_submul_16s_16s_9s_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 9 ),
    .dout_WIDTH( 24 ))
am_submul_16s_16s_9s_24_4_1_U301(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2303_p0),
    .din1(grp_fu_2303_p1),
    .din2(grp_fu_2303_p2),
    .ce(1'b1),
    .dout(grp_fu_2303_p3)
);

FFT_am_addmul_16s_16s_9s_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 9 ),
    .dout_WIDTH( 24 ))
am_addmul_16s_16s_9s_24_4_1_U302(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2312_p0),
    .din1(grp_fu_2312_p1),
    .din2(grp_fu_2312_p2),
    .ce(1'b1),
    .dout(grp_fu_2312_p3)
);

FFT_mac_muladd_16s_8ns_24s_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_8ns_24s_24_4_1_U303(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_2),
    .din1(grp_fu_2321_p1),
    .din2(mul_ln389_38_fu_1835_p2),
    .ce(1'b1),
    .dout(grp_fu_2321_p3)
);

FFT_mac_muladd_16s_9s_24s_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_9s_24s_24_4_1_U304(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_34),
    .din1(grp_fu_2330_p1),
    .din2(mul_ln389_40_fu_1840_p2),
    .ce(1'b1),
    .dout(grp_fu_2330_p3)
);

FFT_mac_muladd_16s_7ns_24s_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_7ns_24s_24_4_1_U305(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_1),
    .din1(grp_fu_2339_p1),
    .din2(mul_ln389_42_fu_1929_p2),
    .ce(1'b1),
    .dout(grp_fu_2339_p3)
);

FFT_mac_muladd_16s_8s_24s_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_8s_24s_24_4_1_U306(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_33),
    .din1(grp_fu_2348_p1),
    .din2(mul_ln389_44_fu_1934_p2),
    .ce(1'b1),
    .dout(grp_fu_2348_p3)
);

FFT_mac_mulsub_16s_7s_24s_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_mulsub_16s_7s_24s_24_4_1_U307(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4),
    .din1(grp_fu_2357_p1),
    .din2(grp_fu_2357_p2),
    .ce(1'b1),
    .dout(grp_fu_2357_p3)
);

FFT_mac_muladd_16s_7s_24s_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_7s_24s_24_4_1_U308(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_32),
    .din1(grp_fu_2366_p1),
    .din2(grp_fu_2366_p2),
    .ce(1'b1),
    .dout(grp_fu_2366_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        sext_ln389_10_reg_2435 <= sext_ln389_10_fu_847_p1;
        sext_ln389_11_reg_2441 <= sext_ln389_11_fu_851_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        sext_ln389_12_reg_2457 <= sext_ln389_12_fu_941_p1;
        sext_ln389_13_reg_2463 <= sext_ln389_13_fu_945_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        sext_ln389_14_reg_2479 <= sext_ln389_14_fu_1035_p1;
        sext_ln389_15_reg_2485 <= sext_ln389_15_fu_1039_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        sext_ln389_28_reg_2553 <= sext_ln389_28_fu_1355_p1;
        sext_ln389_29_reg_2559 <= sext_ln389_29_fu_1359_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        sext_ln389_30_reg_2575 <= sext_ln389_30_fu_1487_p1;
        sext_ln389_31_reg_2581 <= sext_ln389_31_fu_1491_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        sext_ln389_34_reg_2607 <= sext_ln389_34_fu_1675_p1;
        sext_ln389_35_reg_2613 <= sext_ln389_35_fu_1679_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        sext_ln389_36_reg_2619 <= sext_ln389_36_fu_1759_p1;
        sext_ln389_37_reg_2625 <= sext_ln389_37_fu_1763_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        sext_ln389_6_reg_2391 <= sext_ln389_6_fu_637_p1;
        sext_ln389_7_reg_2397 <= sext_ln389_7_fu_641_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        sext_ln389_8_reg_2413 <= sext_ln389_8_fu_753_p1;
        sext_ln389_9_reg_2419 <= sext_ln389_9_fu_757_p1;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        data_OUT_address0 = 64'd31;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        data_OUT_address0 = 64'd30;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        data_OUT_address0 = 64'd29;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        data_OUT_address0 = 64'd28;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        data_OUT_address0 = 64'd27;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        data_OUT_address0 = 64'd26;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        data_OUT_address0 = 64'd25;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        data_OUT_address0 = 64'd23;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        data_OUT_address0 = 64'd22;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        data_OUT_address0 = 64'd21;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        data_OUT_address0 = 64'd20;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        data_OUT_address0 = 64'd19;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        data_OUT_address0 = 64'd18;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        data_OUT_address0 = 64'd17;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        data_OUT_address0 = 64'd24;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        data_OUT_address0 = 64'd16;
    end else begin
        data_OUT_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        data_OUT_address1 = 64'd15;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        data_OUT_address1 = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        data_OUT_address1 = 64'd13;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        data_OUT_address1 = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        data_OUT_address1 = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        data_OUT_address1 = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        data_OUT_address1 = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        data_OUT_address1 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        data_OUT_address1 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        data_OUT_address1 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        data_OUT_address1 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        data_OUT_address1 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        data_OUT_address1 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        data_OUT_address1 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        data_OUT_address1 = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        data_OUT_address1 = 64'd0;
    end else begin
        data_OUT_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        data_OUT_ce0 = 1'b1;
    end else begin
        data_OUT_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        data_OUT_ce1 = 1'b1;
    end else begin
        data_OUT_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        data_OUT_d0 = conv_i2_i66_i_i83_partset_14_fu_2114_p3;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        data_OUT_d0 = conv_i2_i66_i_i83_partset_13_fu_1998_p3;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        data_OUT_d0 = conv_i2_i66_i_i83_partset_12_fu_1920_p3;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        data_OUT_d0 = conv_i2_i66_i_i83_partset_11_fu_1826_p3;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        data_OUT_d0 = conv_i2_i66_i_i83_partset_10_fu_1742_p3;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        data_OUT_d0 = conv_i2_i66_i_i83_partset_s_fu_1648_p3;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        data_OUT_d0 = conv_i2_i66_i_i83_partset_9_fu_1554_p3;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        data_OUT_d0 = conv_i2_i66_i_i83_partset_7_fu_1422_p3;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        data_OUT_d0 = conv_i2_i66_i_i83_partset_6_fu_1290_p3;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        data_OUT_d0 = conv_i2_i66_i_i83_partset_5_fu_1196_p3;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        data_OUT_d0 = conv_i2_i66_i_i83_partset_4_fu_1102_p3;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        data_OUT_d0 = conv_i2_i66_i_i83_partset_3_fu_1008_p3;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        data_OUT_d0 = conv_i2_i66_i_i83_partset_2_fu_914_p3;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        data_OUT_d0 = conv_i2_i66_i_i83_partset_1_fu_820_p3;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        data_OUT_d0 = conv_i2_i66_i_i83_partset_8_fu_718_p3;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        data_OUT_d0 = conv_i2_i66_i_i83_partset_fu_604_p3;
    end else begin
        data_OUT_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        data_OUT_d1 = conv_i2_i66_i_i_partset_14_fu_2093_p3;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        data_OUT_d1 = conv_i2_i66_i_i_partset_13_fu_1977_p3;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        data_OUT_d1 = conv_i2_i66_i_i_partset_12_fu_1899_p3;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        data_OUT_d1 = conv_i2_i66_i_i_partset_11_fu_1805_p3;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        data_OUT_d1 = conv_i2_i66_i_i_partset_10_fu_1721_p3;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        data_OUT_d1 = conv_i2_i66_i_i_partset_s_fu_1627_p3;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        data_OUT_d1 = conv_i2_i66_i_i_partset_9_fu_1533_p3;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        data_OUT_d1 = conv_i2_i66_i_i_partset_7_fu_1401_p3;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        data_OUT_d1 = conv_i2_i66_i_i_partset_6_fu_1269_p3;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        data_OUT_d1 = conv_i2_i66_i_i_partset_5_fu_1175_p3;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        data_OUT_d1 = conv_i2_i66_i_i_partset_4_fu_1081_p3;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        data_OUT_d1 = conv_i2_i66_i_i_partset_3_fu_987_p3;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        data_OUT_d1 = conv_i2_i66_i_i_partset_2_fu_893_p3;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        data_OUT_d1 = conv_i2_i66_i_i_partset_1_fu_799_p3;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        data_OUT_d1 = conv_i2_i66_i_i_partset_8_fu_697_p3;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        data_OUT_d1 = conv_i2_i66_i_i_partset_fu_583_p3;
    end else begin
        data_OUT_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        data_OUT_we0 = 1'b1;
    end else begin
        data_OUT_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        data_OUT_we1 = 1'b1;
    end else begin
        data_OUT_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign conv_i2_i66_i_i83_partset_10_fu_1742_p3 = {{p_r_M_imag_35_fu_1736_p2}, {p_r_M_real_35_fu_1730_p2}};

assign conv_i2_i66_i_i83_partset_11_fu_1826_p3 = {{p_r_M_imag_38_fu_1820_p2}, {p_r_M_real_38_fu_1814_p2}};

assign conv_i2_i66_i_i83_partset_12_fu_1920_p3 = {{p_r_M_imag_41_fu_1914_p2}, {p_r_M_real_41_fu_1908_p2}};

assign conv_i2_i66_i_i83_partset_13_fu_1998_p3 = {{p_r_M_imag_44_fu_1992_p2}, {p_r_M_real_44_fu_1986_p2}};

assign conv_i2_i66_i_i83_partset_14_fu_2114_p3 = {{p_r_M_imag_47_fu_2108_p2}, {p_r_M_real_47_fu_2102_p2}};

assign conv_i2_i66_i_i83_partset_1_fu_820_p3 = {{p_r_M_imag_5_fu_814_p2}, {p_r_M_real_5_fu_808_p2}};

assign conv_i2_i66_i_i83_partset_2_fu_914_p3 = {{p_r_M_imag_8_fu_908_p2}, {p_r_M_real_8_fu_902_p2}};

assign conv_i2_i66_i_i83_partset_3_fu_1008_p3 = {{p_r_M_imag_11_fu_1002_p2}, {p_r_M_real_11_fu_996_p2}};

assign conv_i2_i66_i_i83_partset_4_fu_1102_p3 = {{p_r_M_imag_14_fu_1096_p2}, {p_r_M_real_14_fu_1090_p2}};

assign conv_i2_i66_i_i83_partset_5_fu_1196_p3 = {{p_r_M_imag_17_fu_1190_p2}, {p_r_M_real_17_fu_1184_p2}};

assign conv_i2_i66_i_i83_partset_6_fu_1290_p3 = {{p_r_M_imag_20_fu_1284_p2}, {p_r_M_real_20_fu_1278_p2}};

assign conv_i2_i66_i_i83_partset_7_fu_1422_p3 = {{p_r_M_imag_23_fu_1416_p2}, {p_r_M_real_23_fu_1410_p2}};

assign conv_i2_i66_i_i83_partset_8_fu_718_p3 = {{p_r_M_imag_26_fu_712_p2}, {p_r_M_real_26_fu_706_p2}};

assign conv_i2_i66_i_i83_partset_9_fu_1554_p3 = {{p_r_M_imag_29_fu_1548_p2}, {p_r_M_real_29_fu_1542_p2}};

assign conv_i2_i66_i_i83_partset_fu_604_p3 = {{p_r_M_imag_2_fu_598_p2}, {p_r_M_real_2_fu_592_p2}};

assign conv_i2_i66_i_i83_partset_s_fu_1648_p3 = {{p_r_M_imag_32_fu_1642_p2}, {p_r_M_real_32_fu_1636_p2}};

assign conv_i2_i66_i_i_partset_10_fu_1721_p3 = {{p_r_M_imag_34_fu_1715_p2}, {p_r_M_real_34_fu_1709_p2}};

assign conv_i2_i66_i_i_partset_11_fu_1805_p3 = {{p_r_M_imag_37_fu_1799_p2}, {p_r_M_real_37_fu_1793_p2}};

assign conv_i2_i66_i_i_partset_12_fu_1899_p3 = {{p_r_M_imag_40_fu_1893_p2}, {p_r_M_real_40_fu_1887_p2}};

assign conv_i2_i66_i_i_partset_13_fu_1977_p3 = {{p_r_M_imag_43_fu_1971_p2}, {p_r_M_real_43_fu_1965_p2}};

assign conv_i2_i66_i_i_partset_14_fu_2093_p3 = {{p_r_M_imag_46_fu_2087_p2}, {p_r_M_real_46_fu_2081_p2}};

assign conv_i2_i66_i_i_partset_1_fu_799_p3 = {{p_r_M_imag_4_fu_793_p2}, {p_r_M_real_4_fu_787_p2}};

assign conv_i2_i66_i_i_partset_2_fu_893_p3 = {{p_r_M_imag_7_fu_887_p2}, {p_r_M_real_7_fu_881_p2}};

assign conv_i2_i66_i_i_partset_3_fu_987_p3 = {{p_r_M_imag_10_fu_981_p2}, {p_r_M_real_10_fu_975_p2}};

assign conv_i2_i66_i_i_partset_4_fu_1081_p3 = {{p_r_M_imag_13_fu_1075_p2}, {p_r_M_real_13_fu_1069_p2}};

assign conv_i2_i66_i_i_partset_5_fu_1175_p3 = {{p_r_M_imag_16_fu_1169_p2}, {p_r_M_real_16_fu_1163_p2}};

assign conv_i2_i66_i_i_partset_6_fu_1269_p3 = {{p_r_M_imag_19_fu_1263_p2}, {p_r_M_real_19_fu_1257_p2}};

assign conv_i2_i66_i_i_partset_7_fu_1401_p3 = {{p_r_M_imag_22_fu_1395_p2}, {p_r_M_real_22_fu_1389_p2}};

assign conv_i2_i66_i_i_partset_8_fu_697_p3 = {{p_r_M_imag_25_fu_691_p2}, {p_r_M_real_25_fu_685_p2}};

assign conv_i2_i66_i_i_partset_9_fu_1533_p3 = {{p_r_M_imag_28_fu_1527_p2}, {p_r_M_real_28_fu_1521_p2}};

assign conv_i2_i66_i_i_partset_fu_583_p3 = {{p_r_M_imag_1_fu_577_p2}, {p_r_M_real_1_fu_571_p2}};

assign conv_i2_i66_i_i_partset_s_fu_1627_p3 = {{p_r_M_imag_31_fu_1621_p2}, {p_r_M_real_31_fu_1615_p2}};

assign grp_fu_2123_p1 = 23'd8388558;

assign grp_fu_2132_p1 = 23'd8388558;

assign grp_fu_2141_p1 = 24'd98;

assign grp_fu_2150_p1 = 24'd16777118;

assign grp_fu_2159_p1 = 24'd143;

assign grp_fu_2168_p1 = 24'd16777073;

assign grp_fu_2177_p1 = 24'd182;

assign grp_fu_2186_p1 = 24'd16777034;

assign grp_fu_2195_p1 = 24'd213;

assign grp_fu_2204_p1 = 24'd16777003;

assign grp_fu_2213_p1 = 24'd237;

assign grp_fu_2222_p1 = 24'd16776979;

assign grp_fu_2231_p1 = 23'd49;

assign grp_fu_2231_p2 = ($signed(shl_ln_fu_1299_p3) - $signed(sext_ln389_18_fu_1313_p1));

assign grp_fu_2240_p1 = 23'd49;

assign grp_fu_2240_p2 = ($signed(sext_ln389_20_fu_1337_p1) - $signed(shl_ln389_2_fu_1323_p3));

assign grp_fu_2249_p1 = 23'd8388558;

assign grp_fu_2249_p2 = ($signed(shl_ln389_5_fu_1431_p3) - $signed(sext_ln389_24_fu_1445_p1));

assign grp_fu_2258_p1 = 23'd8388558;

assign grp_fu_2258_p2 = ($signed(sext_ln389_26_fu_1469_p1) - $signed(shl_ln389_7_fu_1455_p3));

assign grp_fu_2267_p1 = 24'd237;

assign grp_fu_2276_p1 = 24'd16776979;

assign grp_fu_2285_p1 = 24'd213;

assign grp_fu_2294_p1 = 24'd16777003;

assign grp_fu_2303_p0 = sext_ln389_32_fu_1581_p1;

assign grp_fu_2303_p1 = sext_ln389_33_fu_1585_p1;

assign grp_fu_2303_p2 = 24'd16777034;

assign grp_fu_2312_p0 = sext_ln389_33_fu_1585_p1;

assign grp_fu_2312_p1 = sext_ln389_32_fu_1581_p1;

assign grp_fu_2312_p2 = 24'd16777034;

assign grp_fu_2321_p1 = 24'd143;

assign grp_fu_2330_p1 = 24'd16777073;

assign grp_fu_2339_p1 = 24'd98;

assign grp_fu_2348_p1 = 24'd16777118;

assign grp_fu_2357_p1 = 23'd8388558;

assign grp_fu_2357_p2 = ($signed(sext_ln389_39_fu_2021_p1) - $signed(shl_ln389_9_fu_2007_p3));

assign grp_fu_2366_p1 = 23'd8388558;

assign grp_fu_2366_p2 = ($signed(sext_ln389_42_fu_2045_p1) - $signed(shl_ln389_10_fu_2031_p3));

assign mul_ln389_10_fu_928_p0 = sext_ln389_9_reg_2419;

assign mul_ln389_10_fu_928_p1 = 24'd212;

assign mul_ln389_12_fu_1017_p0 = sext_ln389_10_reg_2435;

assign mul_ln389_12_fu_1017_p1 = 24'd181;

assign mul_ln389_14_fu_1022_p0 = sext_ln389_11_reg_2441;

assign mul_ln389_14_fu_1022_p1 = 24'd181;

assign mul_ln389_16_fu_1111_p0 = sext_ln389_12_reg_2457;

assign mul_ln389_16_fu_1111_p1 = 24'd142;

assign mul_ln389_18_fu_1116_p0 = sext_ln389_13_reg_2463;

assign mul_ln389_18_fu_1116_p1 = 24'd142;

assign mul_ln389_20_fu_1205_p0 = sext_ln389_14_reg_2479;

assign mul_ln389_20_fu_1205_p1 = 24'd97;

assign mul_ln389_22_fu_1210_p0 = sext_ln389_15_reg_2485;

assign mul_ln389_22_fu_1210_p1 = 24'd97;

assign mul_ln389_28_fu_1563_p0 = sext_ln389_28_reg_2553;

assign mul_ln389_28_fu_1563_p1 = 24'd16777118;

assign mul_ln389_2_fu_739_p1 = 24'd251;

assign mul_ln389_30_fu_1568_p0 = sext_ln389_29_reg_2559;

assign mul_ln389_30_fu_1568_p1 = 24'd16777118;

assign mul_ln389_32_fu_1657_p0 = sext_ln389_30_reg_2575;

assign mul_ln389_32_fu_1657_p1 = 24'd16777073;

assign mul_ln389_34_fu_1662_p0 = sext_ln389_31_reg_2581;

assign mul_ln389_34_fu_1662_p1 = 24'd16777073;

assign mul_ln389_38_fu_1835_p0 = sext_ln389_34_reg_2607;

assign mul_ln389_38_fu_1835_p1 = 24'd16777003;

assign mul_ln389_40_fu_1840_p0 = sext_ln389_35_reg_2613;

assign mul_ln389_40_fu_1840_p1 = 24'd16777003;

assign mul_ln389_42_fu_1929_p0 = sext_ln389_36_reg_2619;

assign mul_ln389_42_fu_1929_p1 = 24'd16776979;

assign mul_ln389_44_fu_1934_p0 = sext_ln389_37_reg_2625;

assign mul_ln389_44_fu_1934_p1 = 24'd16776979;

assign mul_ln389_4_fu_829_p0 = sext_ln389_6_reg_2391;

assign mul_ln389_4_fu_829_p1 = 24'd236;

assign mul_ln389_6_fu_834_p0 = sext_ln389_7_reg_2397;

assign mul_ln389_6_fu_834_p1 = 24'd236;

assign mul_ln389_8_fu_923_p0 = sext_ln389_8_reg_2413;

assign mul_ln389_8_fu_923_p1 = 24'd212;

assign mul_ln389_fu_730_p1 = 24'd251;

assign p_r_M_imag_10_fu_981_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_28 + trunc_ln389_5_fu_966_p4);

assign p_r_M_imag_11_fu_1002_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_28 - trunc_ln389_5_fu_966_p4);

assign p_r_M_imag_13_fu_1075_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_27 + trunc_ln389_7_fu_1060_p4);

assign p_r_M_imag_14_fu_1096_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_27 - trunc_ln389_7_fu_1060_p4);

assign p_r_M_imag_16_fu_1169_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_26 + trunc_ln389_9_fu_1154_p4);

assign p_r_M_imag_17_fu_1190_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_26 - trunc_ln389_9_fu_1154_p4);

assign p_r_M_imag_19_fu_1263_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_25 + trunc_ln389_10_fu_1248_p4);

assign p_r_M_imag_1_fu_577_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_15 + FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_31);

assign p_r_M_imag_20_fu_1284_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_25 - trunc_ln389_10_fu_1248_p4);

assign p_r_M_imag_22_fu_1395_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_24 + trunc_ln389_12_fu_1380_p4);

assign p_r_M_imag_23_fu_1416_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_24 - trunc_ln389_12_fu_1380_p4);

assign p_r_M_imag_25_fu_691_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_23 + trunc_ln389_13_fu_675_p4);

assign p_r_M_imag_26_fu_712_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_23 - trunc_ln389_13_fu_675_p4);

assign p_r_M_imag_28_fu_1527_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_22 + trunc_ln389_15_fu_1512_p4);

assign p_r_M_imag_29_fu_1548_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_22 - trunc_ln389_15_fu_1512_p4);

assign p_r_M_imag_2_fu_598_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_31 - FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_15);

assign p_r_M_imag_31_fu_1621_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_21 + trunc_ln389_17_fu_1606_p4);

assign p_r_M_imag_32_fu_1642_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_21 - trunc_ln389_17_fu_1606_p4);

assign p_r_M_imag_34_fu_1715_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_20 + trunc_ln389_19_fu_1700_p4);

assign p_r_M_imag_35_fu_1736_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_20 - trunc_ln389_19_fu_1700_p4);

assign p_r_M_imag_37_fu_1799_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_19 + trunc_ln389_21_fu_1784_p4);

assign p_r_M_imag_38_fu_1820_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_19 - trunc_ln389_21_fu_1784_p4);

assign p_r_M_imag_40_fu_1893_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_18 + trunc_ln389_23_fu_1878_p4);

assign p_r_M_imag_41_fu_1914_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_18 - trunc_ln389_23_fu_1878_p4);

assign p_r_M_imag_43_fu_1971_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_17 + trunc_ln389_25_fu_1956_p4);

assign p_r_M_imag_44_fu_1992_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_17 - trunc_ln389_25_fu_1956_p4);

assign p_r_M_imag_46_fu_2087_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_16 + trunc_ln389_27_fu_2072_p4);

assign p_r_M_imag_47_fu_2108_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_16 - trunc_ln389_27_fu_2072_p4);

assign p_r_M_imag_4_fu_793_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_30 + trunc_ln389_1_fu_778_p4);

assign p_r_M_imag_5_fu_814_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_30 - trunc_ln389_1_fu_778_p4);

assign p_r_M_imag_7_fu_887_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_29 + trunc_ln389_3_fu_872_p4);

assign p_r_M_imag_8_fu_908_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_29 - trunc_ln389_3_fu_872_p4);

assign p_r_M_real_10_fu_975_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_81 + trunc_ln389_4_fu_957_p4);

assign p_r_M_real_11_fu_996_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_81 - trunc_ln389_4_fu_957_p4);

assign p_r_M_real_13_fu_1069_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_82 + trunc_ln389_6_fu_1051_p4);

assign p_r_M_real_14_fu_1090_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_82 - trunc_ln389_6_fu_1051_p4);

assign p_r_M_real_16_fu_1163_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_83 + trunc_ln389_8_fu_1145_p4);

assign p_r_M_real_17_fu_1184_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_83 - trunc_ln389_8_fu_1145_p4);

assign p_r_M_real_19_fu_1257_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_84 + trunc_ln389_s_fu_1239_p4);

assign p_r_M_real_1_fu_571_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_94 + FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_42);

assign p_r_M_real_20_fu_1278_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_84 - trunc_ln389_s_fu_1239_p4);

assign p_r_M_real_22_fu_1389_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_85 + trunc_ln389_11_fu_1371_p4);

assign p_r_M_real_23_fu_1410_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_85 - trunc_ln389_11_fu_1371_p4);

assign p_r_M_real_25_fu_685_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_86 + FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_7);

assign p_r_M_real_26_fu_706_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_86 - FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_7);

assign p_r_M_real_28_fu_1521_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_87 + trunc_ln389_14_fu_1503_p4);

assign p_r_M_real_29_fu_1542_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_87 - trunc_ln389_14_fu_1503_p4);

assign p_r_M_real_2_fu_592_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_42 - FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_94);

assign p_r_M_real_31_fu_1615_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_88 + trunc_ln389_16_fu_1597_p4);

assign p_r_M_real_32_fu_1636_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_88 - trunc_ln389_16_fu_1597_p4);

assign p_r_M_real_34_fu_1709_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_89 + trunc_ln389_18_fu_1691_p4);

assign p_r_M_real_35_fu_1730_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_89 - trunc_ln389_18_fu_1691_p4);

assign p_r_M_real_37_fu_1793_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_90 + trunc_ln389_20_fu_1775_p4);

assign p_r_M_real_38_fu_1814_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_90 - trunc_ln389_20_fu_1775_p4);

assign p_r_M_real_40_fu_1887_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_91 + trunc_ln389_22_fu_1869_p4);

assign p_r_M_real_41_fu_1908_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_91 - trunc_ln389_22_fu_1869_p4);

assign p_r_M_real_43_fu_1965_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_92 + trunc_ln389_24_fu_1947_p4);

assign p_r_M_real_44_fu_1986_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_92 - trunc_ln389_24_fu_1947_p4);

assign p_r_M_real_46_fu_2081_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_93 + trunc_ln389_26_fu_2063_p4);

assign p_r_M_real_47_fu_2102_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_93 - trunc_ln389_26_fu_2063_p4);

assign p_r_M_real_4_fu_787_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_79 + trunc_ln_fu_769_p4);

assign p_r_M_real_5_fu_808_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_79 - trunc_ln_fu_769_p4);

assign p_r_M_real_7_fu_881_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_80 + trunc_ln389_2_fu_863_p4);

assign p_r_M_real_8_fu_902_p2 = (FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_80 - trunc_ln389_2_fu_863_p4);

assign sext_ln389_10_fu_847_p1 = $signed(FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_98);

assign sext_ln389_11_fu_851_p1 = $signed(FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_11);

assign sext_ln389_12_fu_941_p1 = $signed(FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_99);

assign sext_ln389_13_fu_945_p1 = $signed(FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_10);

assign sext_ln389_14_fu_1035_p1 = $signed(FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_41);

assign sext_ln389_15_fu_1039_p1 = $signed(FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_9);

assign sext_ln389_18_fu_1313_p1 = $signed(shl_ln389_1_fu_1306_p3);

assign sext_ln389_20_fu_1337_p1 = $signed(shl_ln389_3_fu_1330_p3);

assign sext_ln389_24_fu_1445_p1 = $signed(shl_ln389_6_fu_1438_p3);

assign sext_ln389_26_fu_1469_p1 = $signed(shl_ln389_8_fu_1462_p3);

assign sext_ln389_28_fu_1355_p1 = $signed(FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_37);

assign sext_ln389_29_fu_1359_p1 = $signed(FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_5);

assign sext_ln389_30_fu_1487_p1 = $signed(FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_36);

assign sext_ln389_31_fu_1491_p1 = $signed(FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_4);

assign sext_ln389_32_fu_1581_p1 = $signed(FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_35);

assign sext_ln389_33_fu_1585_p1 = $signed(FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_3);

assign sext_ln389_34_fu_1675_p1 = $signed(FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_34);

assign sext_ln389_35_fu_1679_p1 = $signed(FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_2);

assign sext_ln389_36_fu_1759_p1 = $signed(FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_33);

assign sext_ln389_37_fu_1763_p1 = $signed(FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_1);

assign sext_ln389_39_fu_2021_p1 = $signed(shl_ln389_s_fu_2014_p3);

assign sext_ln389_42_fu_2045_p1 = $signed(shl_ln389_11_fu_2038_p3);

assign sext_ln389_6_fu_637_p1 = $signed(FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_96);

assign sext_ln389_7_fu_641_p1 = $signed(FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_13);

assign sext_ln389_8_fu_753_p1 = $signed(FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_97);

assign sext_ln389_9_fu_757_p1 = $signed(FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_12);

assign shl_ln389_10_fu_2031_p1 = FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4;

assign shl_ln389_10_fu_2031_p3 = {{shl_ln389_10_fu_2031_p1}, {8'd0}};

assign shl_ln389_11_fu_2038_p1 = FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4;

assign shl_ln389_11_fu_2038_p3 = {{shl_ln389_11_fu_2038_p1}, {2'd0}};

assign shl_ln389_1_fu_1306_p1 = FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_8;

assign shl_ln389_1_fu_1306_p3 = {{shl_ln389_1_fu_1306_p1}, {2'd0}};

assign shl_ln389_2_fu_1323_p1 = FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_40;

assign shl_ln389_2_fu_1323_p3 = {{shl_ln389_2_fu_1323_p1}, {8'd0}};

assign shl_ln389_3_fu_1330_p1 = FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_40;

assign shl_ln389_3_fu_1330_p3 = {{shl_ln389_3_fu_1330_p1}, {2'd0}};

assign shl_ln389_4_fu_661_p3 = {{FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_39}, {8'd0}};

assign shl_ln389_5_fu_1431_p1 = FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_6;

assign shl_ln389_5_fu_1431_p3 = {{shl_ln389_5_fu_1431_p1}, {8'd0}};

assign shl_ln389_6_fu_1438_p1 = FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_6;

assign shl_ln389_6_fu_1438_p3 = {{shl_ln389_6_fu_1438_p1}, {2'd0}};

assign shl_ln389_7_fu_1455_p1 = FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_38;

assign shl_ln389_7_fu_1455_p3 = {{shl_ln389_7_fu_1455_p1}, {8'd0}};

assign shl_ln389_8_fu_1462_p1 = FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_38;

assign shl_ln389_8_fu_1462_p3 = {{shl_ln389_8_fu_1462_p1}, {2'd0}};

assign shl_ln389_9_fu_2007_p1 = FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_32;

assign shl_ln389_9_fu_2007_p3 = {{shl_ln389_9_fu_2007_p1}, {8'd0}};

assign shl_ln389_s_fu_2014_p1 = FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_32;

assign shl_ln389_s_fu_2014_p3 = {{shl_ln389_s_fu_2014_p1}, {2'd0}};

assign shl_ln_fu_1299_p1 = FFT_complex_ap_fixed_16_8_5_3_0_complex_ap_fixed_16_8_5_3_0_s4_8;

assign shl_ln_fu_1299_p3 = {{shl_ln_fu_1299_p1}, {8'd0}};

assign sub_ln389_3_fu_669_p2 = (24'd0 - shl_ln389_4_fu_661_p3);

assign trunc_ln389_10_fu_1248_p4 = {{grp_fu_2222_p3[23:8]}};

assign trunc_ln389_11_fu_1371_p4 = {{grp_fu_2231_p3[23:8]}};

assign trunc_ln389_12_fu_1380_p4 = {{grp_fu_2240_p3[23:8]}};

assign trunc_ln389_13_fu_675_p4 = {{sub_ln389_3_fu_669_p2[23:8]}};

assign trunc_ln389_14_fu_1503_p4 = {{grp_fu_2249_p3[23:8]}};

assign trunc_ln389_15_fu_1512_p4 = {{grp_fu_2258_p3[23:8]}};

assign trunc_ln389_16_fu_1597_p4 = {{grp_fu_2267_p3[23:8]}};

assign trunc_ln389_17_fu_1606_p4 = {{grp_fu_2276_p3[23:8]}};

assign trunc_ln389_18_fu_1691_p4 = {{grp_fu_2285_p3[23:8]}};

assign trunc_ln389_19_fu_1700_p4 = {{grp_fu_2294_p3[23:8]}};

assign trunc_ln389_1_fu_778_p4 = {{grp_fu_2132_p3[23:8]}};

assign trunc_ln389_20_fu_1775_p4 = {{grp_fu_2303_p3[23:8]}};

assign trunc_ln389_21_fu_1784_p4 = {{grp_fu_2312_p3[23:8]}};

assign trunc_ln389_22_fu_1869_p4 = {{grp_fu_2321_p3[23:8]}};

assign trunc_ln389_23_fu_1878_p4 = {{grp_fu_2330_p3[23:8]}};

assign trunc_ln389_24_fu_1947_p4 = {{grp_fu_2339_p3[23:8]}};

assign trunc_ln389_25_fu_1956_p4 = {{grp_fu_2348_p3[23:8]}};

assign trunc_ln389_26_fu_2063_p4 = {{grp_fu_2357_p3[23:8]}};

assign trunc_ln389_27_fu_2072_p4 = {{grp_fu_2366_p3[23:8]}};

assign trunc_ln389_2_fu_863_p4 = {{grp_fu_2141_p3[23:8]}};

assign trunc_ln389_3_fu_872_p4 = {{grp_fu_2150_p3[23:8]}};

assign trunc_ln389_4_fu_957_p4 = {{grp_fu_2159_p3[23:8]}};

assign trunc_ln389_5_fu_966_p4 = {{grp_fu_2168_p3[23:8]}};

assign trunc_ln389_6_fu_1051_p4 = {{grp_fu_2177_p3[23:8]}};

assign trunc_ln389_7_fu_1060_p4 = {{grp_fu_2186_p3[23:8]}};

assign trunc_ln389_8_fu_1145_p4 = {{grp_fu_2195_p3[23:8]}};

assign trunc_ln389_9_fu_1154_p4 = {{grp_fu_2204_p3[23:8]}};

assign trunc_ln389_s_fu_1239_p4 = {{grp_fu_2213_p3[23:8]}};

assign trunc_ln_fu_769_p4 = {{grp_fu_2123_p3[23:8]}};

endmodule //FFT_FFT_stage_4
